[phases.setup]
nixPkgs = ["nodejs_20"]
cmds = ["npm install -g pnpm@10"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter=blushbite-web run build"]

[start]
cmd = "pnpm --filter=blushbite-web run start"
